# Generated by Django 2.0.2 on 2018-03-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_tablescan_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scan',
            old_name='datetime',
            new_name='end_datetime',
        ),
    ]
