# Generated by Django 2.0.2 on 2018-03-07 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0003_auto_20180307_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
