# Generated by Django 2.0.2 on 2018-03-07 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0005_scan_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
