# Generated by Django 2.0.2 on 2018-03-11 01:38

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0006_auto_20180307_1342'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tablescan',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='tablescan',
            name='datetime',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),
    ]
