# Generated by Django 2.0.2 on 2018-03-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0007_auto_20180311_0138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablescan',
            options={'ordering': ['datetime']},
        ),
        migrations.AddIndex(
            model_name='tablescan',
            index=models.Index(fields=['table', 'datetime'], name='traffic_tab_table_i_2b4148_idx'),
        ),
    ]
