# Generated by Django 2.0.2 on 2018-03-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0008_auto_20180311_0144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tablescan',
            options={},
        ),
        migrations.AlterModelManagers(
            name='tablescan',
            managers=[
            ],
        ),
    ]
