# Generated by Django 2.0.2 on 2018-03-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0009_auto_20180311_1522'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='playerscan',
            index=models.Index(fields=['table_scan', 'entries'], name='traffic_pla_table_s_acc985_idx'),
        ),
    ]
