# Generated by Django 2.0.2 on 2018-03-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0010_auto_20180313_0311'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tablescan',
            name='traffic_tab_table_i_2b4148_idx',
        ),
        migrations.RemoveIndex(
            model_name='playerscan',
            name='traffic_pla_table_s_acc985_idx',
        ),
        migrations.AddField(
            model_name='tablescan',
            name='four_table_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tablescan',
            name='one_tabler_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tablescan',
            name='three_tabler_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tablescan',
            name='two_tabler_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='tablescan',
            index=models.Index(fields=['datetime'], name='traffic_tab_datetim_7c804b_idx'),
        ),
        migrations.AddIndex(
            model_name='playerscan',
            index=models.Index(fields=['entries'], name='traffic_pla_entries_71c04b_idx'),
        ),
    ]
