# Generated by Django 2.0.2 on 2018-03-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0011_auto_20180313_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablescan',
            old_name='four_table_count',
            new_name='four_tabler_count',
        ),
    ]
