# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='max_players',
            field=models.IntegerField(default=6),
        ),
    ]
