# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_table_max_players'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('name',), 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ('room', 'game', 'max_players', 'limit')},
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
