# Generated by Django 2.0.2 on 2018-02-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0003_auto_20171208_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
