# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0004_auto_20171117_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerscan',
            name='player',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='traffic.Player'),
            preserve_default=False,
        ),
    ]
