# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0005_playerscan_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerscan',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='traffic.Player'),
        ),
    ]
