# Generated by Django 2.0.2 on 2018-02-23 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0005_auto_20180223_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scan',
            options={'ordering': ('-datetime',)},
        ),
    ]
