# Generated by Django 2.0.2 on 2018-02-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0006_auto_20180223_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scan',
            options={},
        ),
    ]
