# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0007_auto_20171118_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerscan',
            name='table_scan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='traffic.TableScan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='room',
            field=models.CharField(choices=[('PS', 'PokerStars')], default='PS', max_length=3),
        ),
        migrations.AlterField(
            model_name='scan',
            name='room',
            field=models.CharField(choices=[('PS', 'PokerStars')], default='PS', max_length=3),
        ),
        migrations.AlterField(
            model_name='table',
            name='game',
            field=models.CharField(choices=[('NL', "NL Hold'em"), ('PLO', 'PL Omaha'), ('PLO8', 'PL Omaha H/L'), ('NLO8', 'NL Omaha H/L')], default='NL', max_length=4),
        ),
        migrations.AlterField(
            model_name='table',
            name='limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='table',
            name='room',
            field=models.CharField(choices=[('PS', 'PokerStars')], default='PS', max_length=3),
        ),
        migrations.AlterField(
            model_name='tablescan',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='traffic.Scan'),
        ),
        migrations.AlterField(
            model_name='tablescan',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='traffic.Table'),
        ),
    ]
