# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0008_auto_20171118_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerscan',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='traffic.Player'),
        ),
    ]
