# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0009_auto_20171118_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso',
            field=models.CharField(default='AA', max_length=2, unique=True),
            preserve_default=False,
        ),
    ]
