# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0010_country_iso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
