# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0011_auto_20171119_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanner',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
