# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0013_auto_20171121_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ('room', 'name')},
        ),
    ]
