ALLOWED_TABLES = [('PS', 'Aenna', 'NL', 200, 6),
                  ('PS', 'Aludra', 'NL', 10, 6),
                  ('PS', 'Amundsen', 'NL', 16, 6),
                  ('PS', 'Aquarius Dwarf', 'PLO', 50, 6),
                  ('PS', 'Arp', 'NL', 50, 9),
                  ('PS', 'Baade', 'NL', 50, 6),
                  ('PS', 'Borrelllly', 'NLO8', 2, 6),
                  ('PS', 'Cassiopeia', 'NL', 5000, 6),
                  ('PS', 'Centaurus', 'NL', 1000, 6),
                  ('PS', 'Coma Berenices', 'PLO', 2000, 6),
                  ('PS', 'Devanssay', 'NLO8', 10, 6),
                  ('PS', 'Diotima', 'PLO', 200, 6),
                  ('PS', 'Donati', 'NL', 5, 6),
                  ('PS', 'Dorado', 'PLO', 1000, 6),
                  ('PS', 'Eulalia', 'PLO', 10, 6),
                  ('PS', 'Gotha', 'PLO', 100, 6),
                  ('PS', 'Halley', 'NL', 2, 6),
                  ('PS', 'Hartley', 'NL', 10, 9),
                  ('PS', 'Humason', 'PLO', 500, 6),
                  ('PS', 'Hyakutake', 'NL', 5, 9),
                  ('PS', 'Hydra', 'NL', 25, 6),
                  ('PS', 'Lambda Velorum', 'NL', 500, 6),
                  ('PS', 'Lovejoy', 'PLO', 2, 6),
                  ('PS', 'Lupus', 'NL', 2000, 6),
                  ('PS', 'Lynx', 'PLO', 5, 6),
                  ('PS', 'McNaught', 'NL', 2, 9),
                  ('PS', 'Nansen', 'NL', 16, 9),
                  ('PS', 'Perseus', 'PLO', 5000, 6),
                  ('PS', 'Serpens Caput', 'PLO8', 50, 6),
                  ('PS', 'Thyestes', 'PLO', 25, 6),
                  ('PS', 'Triangulum', 'NL', 100, 6),
                  ('PS', 'Whirlpool', 'NL', 50, 9)]
